// <auto-generated />
namespace RC_X.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddEnterprise : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEnterprise));
        
        string IMigrationMetadata.Id
        {
            get { return "201703281658549_AddEnterprise"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
